### PR TITLE
Re2 rebuild

### PR DESCRIPTION
**Pull request by jstkdng**
Nothing interesting, just increased the pkgrel to update the aur.
Just realized my GPG key expired, lol.
Edit: also removed the ungoogled-chromium submodule as it is no longer required

### CODE REVIEW

**Comment by wchen342** [comment]
Maybe we should just put a warning somewhere telling people to recompile whenever some system library got updated, unless you want to manually increase version number every time this happens..

**Comment by jstkdng** [comment]
increasing the pkgrel is standard on arch whenever a rebuild is needed.

**Comment by wchen342** [comment]
I see. BTW is there a way to know a rebuild is needed other than waiting for reports?

**Comment by jstkdng** [comment]
There are tools like urlwatch but haven't set it up yet.

**Comment by morguldir** [comment]
I do not recommend doing this for AUR packages, the reason it is done in the official repos is that the local databases ensure that they only rebuild if they upgraded the library, and because the maintainers cooperate, the pkgrel bump happens at pretty much the same time, meaning the rebuild should only happen once and when it is required. An accidental rebuild is also more impactful for a user than for a mirror, especially for a package like chromium.

In the AUR however, you can't instantly push this rebuild, which means that some users have already rebuilt it. Also because the AUR doesn't use local databases, some may not have upgraded their system yet, and end up rebuilding for no reason.

Here is a note in the wiki indicating that it's the users responsibility to rebuild: 
> Note: The AUR is unsupported, so any packages you install are your responsibility to update, not pacman's. If packages in the official repositories are updated, you will need to rebuild any AUR packages that depend on those libraries.

https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_and_upgrading_packages

**Comment by jstkdng** [comment]
Well, there are many people with different opinions. Bumping the pkgrel signals pacman/AUR helpers an update is needed, and it just helps on the user side. It also helps to keep version consistency between binary repositories and AUR packages.
You are free to not bump the pkgrel on the packages you maintain though.

**Comment by Scimmia22** [comment]
The thing is, you have no idea when the packages need a rebuild on the user's side. What if they use use the testing repos? What if they're holding something back? What if they're on a different distro? You're making unwarranted assumptions and annoying users who know what they're doing.

**Comment by jstkdng** [comment]
@Scimmia22 

>What if they're on a different distro?

This is the archlinux repository

>What if they use use the testing repos?

If you decide to use those, you are on your own.

>annoying users who know what they're doing.

This kind of user isn't the mayority, and if you are one of those users you should know when it is truly required to rebuild and disregard the decisions anyone makes.

**Comment by wchen342** [comment]
Isn't it possible to force a minimum version of a required package?

**Comment by Rowisi** [comment]
Wouldn't it be better if we build and put re2 library inside chromium folder and upgrade it alongside UC version upgrades?

**Comment by jstkdng** [comment]
@Rowisi 
Its not just re2, at one point libjsoncpp broke chromium as well, that is the drawback of dynamic linking. If you no longer want to experience it use guix or uc-portablelinux.

@wchen342
yes, you can set a minimum version for a dependency but that wont really help here.

**Comment by wchen342** [comment]
At least that will prevent the case when someone hasn't/doesn't want to upgrade their system package and rebuild this one. Won't prevent rebuilding in advance though.

**Comment by jstkdng** [comment]
There's no silver bullet that will solves everyone's problem as everyone is in a different situation. If we don't bump the pkgrel we will get reports from users like #90 , #77 or https://github.com/jstkdng/ungoogled-chromium-archlinux/issues/19 , and if we do decide to bump pkgrel we will get comments like the ones from @morguldir or @Scimmia22 .
Let's just keep it KISS and do how Arch does it.

**Pull request merged**
