### PR TITLE
85.0.4183.83 upgrade

### PR DESCRIPTION
**Pull request by jstkdng**

### CODE REVIEW

**Comment by wchen342** [comment]
What happened to libvpx? Btw just noticed, why the name `_gcc_patchset` cause it seems to have nothing to do with gcc?

**Comment by jstkdng** [comment]
Chromium 85 switched to ANGLE and that broke some stuff, arch's libvpx and vaapi being one of those, it also introduced some graphics glitches. `_gcc_patchset` is used to fix linking with libstdc++, not related to the compiler.

**Comment by Mathew-D** [comment]
The package works for me. Thanks.

**Comment by wchen342** [comment]
Looks good, merging.

**Pull request merged**
