### PR TITLE
Update to 77.0.3865.90-1 [ci skip]

### PR DESCRIPTION
**Pull request by nikolowry**
Patch changes are documented in #30. 

I'd like to eventually refine the CI workflow for version updates. I feel somewhat silly tagging with `[ci skip]` when these types of changes are should require verifying `PKGBUILD`'s  `prepare`.

### CODE REVIEW

**Comment by jstkdng** [comment]
It seems you included the vaapi.patch into the upstream, it has offset issues though. Fixing them first might be nice.

**Comment by howaboutsynergy** [comment]
Any idea what could be the cause/fix for this?

<details>

```
[917/3/49/968] 3.525s [remaining/running/finished/totalthissession] elapsed
ccache clang++ -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -pie -Wl,--disable-new-dtags -Wl,-O1,--sort-common,--as-needed,-z,relro -o "./chromedriver" -Wl,--start-group @"./chromedriver.rsp"  -Wl,--end-group   -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -licui18n -licuuc -licudata -lX11 -lX11-xcb -lxcb -lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lXtst -levent -lresolv -lgio-2.0 -lz -ljpeg -lminizip -lXss -ldbus-1 -lfontconfig -lwebpdemux -lwebpmux -lwebp -lfreetype -lexpat -lharfbuzz-subset -lharfbuzz -ldrm -lXrandr -lre2 
FAILED: chromedriver 
ccache clang++ -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -pie -Wl,--disable-new-dtags -Wl,-O1,--sort-common,--as-needed,-z,relro -o "./chromedriver" -Wl,--start-group @"./chromedriver.rsp"  -Wl,--end-group   -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -licui18n -licuuc -licudata -lX11 -lX11-xcb -lxcb -lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lXtst -levent -lresolv -lgio-2.0 -lz -ljpeg -lminizip -lXss -ldbus-1 -lfontconfig -lwebpdemux -lwebpmux -lwebp -lfreetype -lexpat -lharfbuzz-subset -lharfbuzz -ldrm -lXrandr -lre2 
ld.lld: error: undefined symbol: Cr_z_inflateInit_
>>> referenced by cert_compressor.cc:591 (../../net/third_party/quiche/src/quic/core/crypto/cert_compressor.cc:591)
>>>               net/cert_compressor.o:(quic::CertCompressor::DecompressChain(base::BasicStringPiece<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, quic::CommonCertSets const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflate
>>> referenced by cert_compressor.cc:596 (../../net/third_party/quiche/src/quic/core/crypto/cert_compressor.cc:596)
>>>               net/cert_compressor.o:(quic::CertCompressor::DecompressChain(base::BasicStringPiece<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, quic::CommonCertSets const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflateSetDictionary
>>> referenced by cert_compressor.cc:600 (../../net/third_party/quiche/src/quic/core/crypto/cert_compressor.cc:600)
>>>               net/cert_compressor.o:(quic::CertCompressor::DecompressChain(base::BasicStringPiece<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, quic::CommonCertSets const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflate
>>> referenced by cert_compressor.cc:603 (../../net/third_party/quiche/src/quic/core/crypto/cert_compressor.cc:603)
>>>               net/cert_compressor.o:(quic::CertCompressor::DecompressChain(base::BasicStringPiece<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, quic::CommonCertSets const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflateEnd
>>> referenced by cert_compressor.cc:439 (../../net/third_party/quiche/src/quic/core/crypto/cert_compressor.cc:439)
>>>               net/cert_compressor.o:(quic::CertCompressor::DecompressChain(base::BasicStringPiece<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, quic::CommonCertSets const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflateEnd
>>> referenced by cert_compressor.cc:439 (../../net/third_party/quiche/src/quic/core/crypto/cert_compressor.cc:439)
>>>               net/cert_compressor.o:(quic::CertCompressor::DecompressChain(base::BasicStringPiece<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, quic::CommonCertSets const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_crc32
>>> referenced by simple_util.cc:117 (../../net/disk_cache/simple/simple_util.cc:117)
>>>               net/simple_util.o:(disk_cache::simple_util::Crc32(char const*, int)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_crc32
>>> referenced by simple_util.cc:120 (../../net/disk_cache/simple/simple_util.cc:120)
>>>               net/simple_util.o:(disk_cache::simple_util::Crc32(char const*, int)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_crc32
>>> referenced by simple_util.cc:124 (../../net/disk_cache/simple/simple_util.cc:124)
>>>               net/simple_util.o:(disk_cache::simple_util::IncrementalCrc32(unsigned int, char const*, int)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_crc32
>>> referenced by simple_entry_impl.cc:1092 (../../net/disk_cache/simple/simple_entry_impl.cc:1092)
>>>               net/simple_entry_impl.o:(disk_cache::SimpleEntryImpl::ReadDataInternal(bool, int, int, net::IOBuffer*, int, base::OnceCallback<void (int)>)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_crc32
>>> referenced by simple_entry_impl.cc:981 (../../net/disk_cache/simple/simple_entry_impl.cc:981)
>>>               net/simple_entry_impl.o:(disk_cache::SimpleEntryImpl::CloseInternal()) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_crc32
>>> referenced by simple_entry_impl.cc:1189 (../../net/disk_cache/simple/simple_entry_impl.cc:1189)
>>>               net/simple_entry_impl.o:(disk_cache::SimpleEntryImpl::WriteDataInternal(int, int, net::IOBuffer*, int, base::OnceCallback<void (int)>, bool)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_crc32
>>> referenced by simple_synchronous_entry.cc:285 (../../net/disk_cache/simple/simple_synchronous_entry.cc:285)
>>>               net/simple_synchronous_entry.o:(disk_cache::SimpleEntryCreationResults::SimpleEntryCreationResults(disk_cache::SimpleEntryStat)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_crc32
>>> referenced by simple_synchronous_entry.cc:285 (../../net/disk_cache/simple/simple_synchronous_entry.cc:285)
>>>               net/simple_synchronous_entry.o:(disk_cache::SimpleEntryCreationResults::SimpleEntryCreationResults(disk_cache::SimpleEntryStat)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflateEnd
>>> referenced by gzip_source_stream.cc:36 (../../net/filter/gzip_source_stream.cc:36)
>>>               net/gzip_source_stream.o:(net::GzipSourceStream::~GzipSourceStream()) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflateEnd
>>> referenced by gzip_source_stream.cc:36 (../../net/filter/gzip_source_stream.cc:36)
>>>               net/gzip_source_stream.o:(net::GzipSourceStream::~GzipSourceStream()) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflateInit2_
>>> referenced by gzip_source_stream.cc:66 (../../net/filter/gzip_source_stream.cc:66)
>>>               net/gzip_source_stream.o:(net::GzipSourceStream::Create(std::unique_ptr<net::SourceStream, std::default_delete<net::SourceStream> >, net::SourceStream::SourceType)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflateInit_
>>> referenced by gzip_source_stream.cc:68 (../../net/filter/gzip_source_stream.cc:68)
>>>               net/gzip_source_stream.o:(net::GzipSourceStream::Create(std::unique_ptr<net::SourceStream, std::default_delete<net::SourceStream> >, net::SourceStream::SourceType)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflate
>>> referenced by gzip_source_stream.cc:139 (../../net/filter/gzip_source_stream.cc:139)
>>>               net/gzip_source_stream.o:(net::GzipSourceStream::FilterData(net::IOBuffer*, int, net::IOBuffer*, int, int*, bool)) in archive obj/net/libnet.a

ld.lld: error: undefined symbol: Cr_z_inflateReset
>>> referenced by gzip_source_stream.cc:256 (../../net/filter/gzip_source_stream.cc:256)
>>>               net/gzip_source_stream.o:(net::GzipSourceStream::FilterData(net::IOBuffer*, int, net::IOBuffer*, int, int*, bool)) in archive obj/net/libnet.a

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

</details>

I haven't fully applied your PR and I'm using the git version with `gclient sync --revision=src@77.0.3865.90`, so this may be why you're not hitting this.

Those symbols like `Cr_z_inflateInit_` seem to be appearing only in:
`third_party/zlib/chromeconf.h:121:#define inflateInit_ Cr_z_inflateInit_`
but nothing is including that `chromeconf.h` except `third_party/zlib/zconf.h`:
```
  #if !defined(CHROMIUM_ZLIB_NO_CHROMECONF)
  /* This include does prefixing as below, but with an updated set of names.  Al  so
   * sets up export macros in component builds. */
  #include "chromeconf.h"                                                       
  #endif
```
So it seems like `CHROMIUM_ZLIB_NO_CHROMECONF` isn't defined anywhere(also according to `grep`) but where/what would define it?

If I simply comment out that `#include "chromeconf.h" `, the compilation seems to continue(well, it recompiles stuff from 1400 files left (was about 900 before the change))

(side note: I'm compiling on laptop, so full build is about 6 hours ie. slow)

**Comment by jstkdng** [comment]
probably you haven't applied the arch's zlib patch

**Comment by howaboutsynergy** [comment]
> probably you haven't applied the arch's zlib patch

initially I haven't (if you mean [this arch linux patch](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/1a71ba33500fa56d766a46d06b2b08a57cef8bff/patches/archlinux/system/zlib.patch)) but before posting that comment I did apply it locally (by undoing the debian/courgette [one](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/30#issuecomment-533893992) first) buuut what i didn't do afterwards was a 'gn gen' again... I'll try that a bit later, now I'm still compiling with that commented out include and I still haven't hit the linking for chromedriver(which is where it would fail) even though I'm at 700 files left to compile. `[691/6/460/1156] 2652.346s [remaining/running/finished/totalthissession] elapsed`

**Comment by nikolowry** [comment]
@howaboutsynergy are you not running a system with `makepkg`? Using the Chromium tags' tarball has always proven to be way quicker than using `gclient` for desktop builds. I only use `gclient` in my `bromite-builder` repo, https://github.com/nikolowry/bromite-builder, because there's really no other way for Android.

If you can build with `makepkg` consider @jstkdng's fork or my fork (you'll have to change https://github.com/nikolowry/ungoogled-chromium-archlinux/blob/master/PKGBUILD#L39 to point to git+https://github.com/nikolowry/ungoogled-chromium-archlinux.git#commit=${_ungoogled_archlinux_version})

@jstkdng I'll update tomorrow when I have some down time

**Comment by howaboutsynergy** [comment]
> @howaboutsynergy are you not running a system with `makepkg`? 

I am indeed, on ArchLinux.
> Using the Chromium tags' tarball has always proven to be way quicker than using `gclient` for desktop builds.

Definitely quicker with tarball. But I decided to use chromium from git source via [these](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md#Get-the-code) instructions, more or less.

> If you can build with `makepkg` consider @jstkdng's fork or my fork (you'll have to change https://github.com/nikolowry/ungoogled-chromium-archlinux/blob/master/PKGBUILD#L39 to point to git+[https://github.com/nikolowry/ungoogled-chromium-archlinux.git#commit=${_ungoogled_archlinux_version}](https://github.com/nikolowry/ungoogled-chromium-archlinux.git#commit=$%7B_ungoogled_archlinux_version%7D))
> 
> @jstkdng I'll update tomorrow when I have some down time

Thanks I'll try those suggestions! I was having trouble thinking about how to apply this PR properly and that's a great way to... at least test it.

Re my prev. [comment(s)](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/32#issuecomment-534375753), the commented out include seems to have worked(no linker error):
```
[288/6/681/974] 3659.083s [remaining/running/finished/totalthissession] elapsed
ccache clang++ -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -pie -Wl,--disable-new-dtags -Wl,-O1,--sort-common,--as-needed,-z,relro -o "./chromedriver" -Wl,--start-group @"./chromedriver.rsp"  -Wl,--end-group   -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -licui18n -licuuc -licudata -lX11 -lX11-xcb -lxcb -lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lXtst -levent -lresolv -lgio-2.0 -lz -ljpeg -lminizip -lXss -ldbus-1 -lfontconfig -lwebpdemux -lwebpmux -lwebp -lfreetype -lexpat -lharfbuzz-subset -lharfbuzz -ldrm -lXrandr -lre2 
```

I'll also try the `gn gen` rerun and then the forks and update this comment so I don't spam much.

Thanks for the help!

**Comment by howaboutsynergy** [comment]
> It seems you included the vaapi.patch into the upstream, it has offset issues though. Fixing them first might be nice.

```
INFO: * Applying vaapi.patch (13/19)
DEBUG: /home/user/bin/binprio/patch --fuzz=2 -p1 --ignore-whitespace -i /home/user/build/1packages/4used/chro3/ungoogled-chromium-archlinux/makepkg_pacman/ungoogled-chromium/src/ungoogled-chromium-archlinux/patches/archlinux/fixes/vaapi.patch -d . --no-backup-if-mismatch --forward
patching file media/gpu/gpu_video_decode_accelerator_factory.cc
Hunk #1 succeeded at 171 (offset -12 lines).
patching file media/gpu/vaapi/vaapi_video_decode_accelerator.cc
Hunk #1 succeeded at 63 (offset -1 lines).
Hunk #2 succeeded at 79 (offset -1 lines).
Hunk #3 succeeded at 636 with fuzz 1 (offset 4 lines).
Hunk #4 succeeded at 656 with fuzz 1 (offset 4 lines).
Hunk #5 succeeded at 663 (offset 2 lines).
Hunk #6 succeeded at 1094 (offset 14 lines).
Hunk #7 succeeded at 1132 (offset 17 lines).
patching file media/gpu/vaapi/vaapi_wrapper.cc
Hunk #1 succeeded at 323 (offset 57 lines).
Hunk #2 succeeded at 365 (offset 58 lines).
Hunk #3 succeeded at 402 (offset 58 lines).
```

After applying the above, on my chromium git, and comparing for offset differences, I get this:

<details>

```diff
$ colordiff -up /home/user/build/1packages/4used/chro3/ungoogled-chromium-archlinux/makepkg_pacman/ungoogled-chromium/src/ungoogled-chromium-archlinux/patches/archlinux/fixes/vaapi.patch /tmp/le.patch
--- /home/user/build/1packages/4used/chro3/ungoogled-chromium-archlinux/makepkg_pacman/ungoogled-chromium/src/ungoogled-chromium-archlinux/patches/archlinux/fixes/vaapi.patch	2019-09-24 07:07:35.413189005 +0200
+++ /tmp/le.patch	2019-09-24 07:25:42.995516243 +0200
@@ -1,19 +1,8 @@
-From fe61d25580bd22d68b20323e7cd684dcba0cd3f4 Mon Sep 17 00:00:00 2001
-From: Akarshan Biswas <akarshanbiswas@fedoraproject.org>
-Date: Tue, 9 Jul 2019 18:39:54 +0530
-Subject: [PATCH] Disable VAProfileNone on Linux and fix vaapi drm
-
----
- .../gpu_video_decode_accelerator_factory.cc   |  2 ++
- .../vaapi/vaapi_video_decode_accelerator.cc   | 21 ++++++++++++++++
- media/gpu/vaapi/vaapi_wrapper.cc              | 24 +++++++++++++++----
- 3 files changed, 42 insertions(+), 5 deletions(-)
-
 diff --git a/media/gpu/gpu_video_decode_accelerator_factory.cc b/media/gpu/gpu_video_decode_accelerator_factory.cc
-index dc9ff3fb3..53189759c 100644
+index f9787be0a3a7..ba95fab25156 100644
 --- a/media/gpu/gpu_video_decode_accelerator_factory.cc
 +++ b/media/gpu/gpu_video_decode_accelerator_factory.cc
-@@ -183,6 +183,8 @@ GpuVideoDecodeAcceleratorFactory::CreateVDA(
+@@ -171,6 +171,8 @@ GpuVideoDecodeAcceleratorFactory::CreateVDA(
      vda = (this->*create_vda_function)(workarounds, gpu_preferences, media_log);
      if (vda && vda->Initialize(config, client))
        return vda;
@@ -23,10 +12,10 @@ index dc9ff3fb3..53189759c 100644
  
    return nullptr;
 diff --git a/media/gpu/vaapi/vaapi_video_decode_accelerator.cc b/media/gpu/vaapi/vaapi_video_decode_accelerator.cc
-index 3c1316dca..a5fa64b5a 100644
+index 95df4498b43b..1dcad1530e16 100644
 --- a/media/gpu/vaapi/vaapi_video_decode_accelerator.cc
 +++ b/media/gpu/vaapi/vaapi_video_decode_accelerator.cc
-@@ -64,6 +64,9 @@ void ReportToUMA(VAVDADecoderFailure failure) {
+@@ -63,6 +63,9 @@ void ReportToUMA(VAVDADecoderFailure failure) {
                              VAVDA_DECODER_FAILURES_MAX + 1);
  }
  
@@ -36,7 +25,7 @@ index 3c1316dca..a5fa64b5a 100644
  // Returns true if the CPU is an Intel Gemini Lake or later (including Kaby
  // Lake) Cpu platform id's are referenced from the following file in kernel
  // source arch/x86/include/asm/intel-family.h
-@@ -77,6 +80,8 @@ bool IsGeminiLakeOrLater() {
+@@ -76,6 +79,8 @@ bool IsGeminiLakeOrLater() {
    return is_geminilake_or_later;
  }
  
@@ -45,8 +34,8 @@ index 3c1316dca..a5fa64b5a 100644
  }  // namespace
  
  #define RETURN_AND_NOTIFY_ON_FAILURE(result, log, error_code, ret) \
-@@ -627,6 +632,13 @@ void VaapiVideoDecodeAccelerator::AssignPictureBuffers(
-   const unsigned int va_format = GetVaFormatForVideoCodecProfile(profile_);
+@@ -631,6 +636,13 @@ void VaapiVideoDecodeAccelerator::AssignPictureBuffers(
+   va_surface_format_ = GetVaFormatForVideoCodecProfile(profile_);
    std::vector<VASurfaceID> va_surface_ids;
  
 +  // Nvidia doesn't support VAProfileNone, so don't try to create a temporary
@@ -59,15 +48,14 @@ index 3c1316dca..a5fa64b5a 100644
    // If we aren't in BufferAllocationMode::kNone, we have to allocate a
    // |vpp_vaapi_wrapper_| for VaapiPicture to DownloadFromSurface() the VA's
    // internal decoded frame.
-@@ -640,6 +652,7 @@ void VaapiVideoDecodeAccelerator::AssignPictureBuffers(
+@@ -644,15 +656,20 @@ void VaapiVideoDecodeAccelerator::AssignPictureBuffers(
        NotifyError(PLATFORM_FAILURE);
      }
    }
 +  #endif
  
    for (size_t i = 0; i < buffers.size(); ++i) {
-     DCHECK(requested_pic_size_ == buffers[i].size());
-@@ -648,9 +661,13 @@ void VaapiVideoDecodeAccelerator::AssignPictureBuffers(
+     // If we aren't in BufferAllocationMode::kNone, this |picture| is
      // only used as a copy destination. Therefore, the VaapiWrapper used and
      // owned by |picture| is |vpp_vaapi_wrapper_|.
      std::unique_ptr<VaapiPicture> picture = vaapi_picture_factory_->Create(
@@ -81,7 +69,7 @@ index 3c1316dca..a5fa64b5a 100644
          make_context_current_cb_, bind_image_cb_, buffers[i]);
      RETURN_AND_NOTIFY_ON_FAILURE(picture, "Failed creating a VaapiPicture",
                                   PLATFORM_FAILURE, );
-@@ -1063,6 +1080,9 @@ VaapiVideoDecodeAccelerator::GetSupportedProfiles() {
+@@ -1077,6 +1094,9 @@ VaapiVideoDecodeAccelerator::GetSupportedProfiles() {
  
  VaapiVideoDecodeAccelerator::BufferAllocationMode
  VaapiVideoDecodeAccelerator::DecideBufferAllocationMode() {
@@ -91,7 +79,7 @@ index 3c1316dca..a5fa64b5a 100644
    // TODO(crbug.com/912295): Enable a better BufferAllocationMode for IMPORT
    // |output_mode_| as well.
    if (output_mode_ == VideoDecodeAccelerator::Config::OutputMode::IMPORT)
-@@ -1095,6 +1115,7 @@ VaapiVideoDecodeAccelerator::DecideBufferAllocationMode() {
+@@ -1112,6 +1132,7 @@ VaapiVideoDecodeAccelerator::DecideBufferAllocationMode() {
      return BufferAllocationMode::kReduced;
  
    return BufferAllocationMode::kSuperReduced;
@@ -100,10 +88,10 @@ index 3c1316dca..a5fa64b5a 100644
  
  bool VaapiVideoDecodeAccelerator::IsBufferAllocationModeReducedOrSuperReduced()
 diff --git a/media/gpu/vaapi/vaapi_wrapper.cc b/media/gpu/vaapi/vaapi_wrapper.cc
-index f6008d288..d829582a6 100644
+index 7df60e273324..7d87f6d5cd04 100644
 --- a/media/gpu/vaapi/vaapi_wrapper.cc
 +++ b/media/gpu/vaapi/vaapi_wrapper.cc
-@@ -266,6 +266,10 @@ void VADisplayState::PreSandboxInitialization() {
+@@ -323,6 +323,10 @@ void VADisplayState::PreSandboxInitialization() {
        base::File::FLAG_OPEN | base::File::FLAG_READ | base::File::FLAG_WRITE);
    if (drm_file.IsValid())
      VADisplayState::Get()->SetDrmFd(drm_file.GetPlatformFile());
@@ -114,7 +102,7 @@ index f6008d288..d829582a6 100644
  }
  
  VADisplayState::VADisplayState()
-@@ -303,10 +307,11 @@ bool VADisplayState::InitializeOnce() {
+@@ -361,10 +365,11 @@ bool VADisplayState::InitializeOnce() {
      case gl::kGLImplementationDesktopGL:
  #if defined(USE_X11)
        va_display_ = vaGetDisplay(gfx::GetXDisplay());
@@ -129,7 +117,7 @@ index f6008d288..d829582a6 100644
        break;
      // Cannot infer platform from GL, try all available displays
      case gl::kGLImplementationNone:
-@@ -339,8 +344,17 @@ bool VADisplayState::InitializeOnce() {
+@@ -397,8 +402,17 @@ bool VADisplayState::InitializeOnce() {
    int major_version, minor_version;
    VAStatus va_res = vaInitialize(va_display_, &major_version, &minor_version);
    if (va_res != VA_STATUS_SUCCESS) {
@@ -149,5 +137,3 @@ index f6008d288..d829582a6 100644
    }
  
    va_initialized_ = true;
--- 
-2.21.0
```

</details>

hope this helps or something

**Comment by Eloston** [comment]
Sorry, I'm missing the context on this. What's the reason for `[ci skip]`?

**Comment by nikolowry** [comment]
@Eloston I know CI will fail because the commit hash doesn't exist in this repo yet

**Comment by Eloston** [comment]
@nikolowry I'm still not able to see the problem. I'm guessing the problematic CI task is `validate_makepkg_task`, but I don't see anything in the commands that run or the PKGBUILD itself that would cause a check on this repo's hash?

**Comment by nikolowry** [comment]
@Eloston yep, all the checks can't be done in a potential PR until they've actually been pulled into this repo. 

But for this go around, I was at least able to run the CI tasks by making a temp branch in my fork and replacing this repo's remote with my fork's remote in the `PKGBUILD`'s source. As long as we don't have a hash collision right now, everything should merge in properly.

But the whole workflow is counter intuitive -- reviewing PRs like this won't be sustainable.

As I see it, there's really only two options we could explore for future releases:

1) Focus on making at the very least a master/shared "Linux" patchset repo (related discussionhttps://github.com/Eloston/ungoogled-chromium/issues/827). Then only ArchLinux specific patches would get checked in here and we'll have to add them directly o the source array. Killing the need to checkout this repo would solve this "chicken or egg" problem.

2) If we keep it as is, we'll need to extend the devutils to be able to generate tmp `PKGBUILD`'s for PRs that would basically automate what I did for this build https://cirrus-ci.com/build/5438960035168256

**Comment by Eloston** [comment]
@nikolowry I've moved this discussion to #34. Regarding this PR, we don't have to let #34 block this PR; let me know when it's ready for review.

**Comment by nikolowry** [comment]
@Eloston it's ready -- let me know if you need any changes

**Pull request merged**
