### PR TITLE
Upstream chromium upgrade

### PR DESCRIPTION
**Pull request by jstkdng**
I've also been working on updating the build workflow, and it works but it takes >20 hours. Tried the distcc approach but no good results came out of it.

### CODE REVIEW

**Comment by jstkdng** [comment]
oops, almost forgot to remove the packager, what should we put there?

**Comment by jstkdng** [comment]
@wchen342 @braewoods could you take a look?

**Comment by wchen342** [comment]
Is it distributed or not? I saw distcc but only one instance is used?

**Comment by jstkdng** [comment]
where did you see distcc? And this isnt distributed, each job starts the next one after finishing.

**Comment by jstkdng** [comment]
That is why I said it takes 20 hours.

**Comment by wchen342** [comment]
Oh that's `BUILDENV`, I thought it's cmdline flags. It's going to take longer because of the Ubuntu machine specs but the `.yml` file sure looks a lot clearer and easier to maintain.

**Comment by jstkdng** [comment]
yeah, it should be. If another build step is required just copy and paste it before the package job.
Does mac runners have more resources?

**Comment by wchen342** [comment]
Yeah the Mac ones have 4 cores and 12GB memory if I remember correctly. And I think they have a lot more disk spaces too.

**Comment by jstkdng** [comment]
if it has more ram we could use that as a tmpfs. Will test some stuff with it.

**Comment by wchen342** [comment]
I tested it before but I didn't see a lot of improvements on compiling time. Either it was because of `docker` in the middle, or I did something wrong. You can test it your way and it will be good if you can get compiling time under 12 hours.

**Comment by jstkdng** [comment]
Github seems to be having issues in regards to uploading actions, as seen here: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/runs/782282723
Also, 4 build stages could not be enough to build chromium due to low resources. How could we fix that?
MacOS runners has more resources the ubuntu runners, what about windows runners? Regarding the upload of artifacts, could we use another service like anonfiles or transfer.sh?

**Comment by wchen342** [comment]
> Github seems to be having issues in regards to uploading actions

Oh right, there are some problems with their uploads since they upgraded to v2. They are solving the problem but I don't know how long the problem will persist.

> what about windows runners

I think they are they same as Ubuntu ones, but I didn't test.

> could we use another service like anonfiles or transfer.sh

Then you will need to register a user and use their API or something? Also this adds the need to verify the contents after downloading.

**Comment by braewoods** [comment]
This sounds like a lot of hoops to jump through. What is the benefit of it all? OBS is far easier to setup and is much faster. The only real drawback is that it's not suitable for pull requests due to it needing a single target to build for.

**Comment by wchen342** [comment]
Yeah I agree on this one, OBS seems a lot easier to do.
@braewoods btw what step is the OBS build of Arch repo stalled at?

**Comment by braewoods** [comment]
@wchen342 Most unresolved questions about how to handle OBS credentials and possibly splitting the Arch stuff into multiple flavors. I thought it best to resolve that before doing more as I hate redoing work.

**Comment by jstkdng** [comment]
welp, the build "failed" even though a package was created during the last part.
I guess this can be merged.

**Comment by wchen342** [comment]
I will suggest [adding a test step at the end](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/87/files#diff-898e737ee4e56ba042bda31764bed49eL365) but that can be done later. I'm merging this now.

**Pull request merged**
