### PR TITLE
Update to 80.0.3987.122

### PR DESCRIPTION
**Pull request by wchen342**

### CODE REVIEW

**Comment by braewoods** [comment]
Doesn't _ungoogled_archlinux_version also need to be updated?

**Comment by wchen342** [comment]
Oh yeah forgot that. How do you do that in one step?

**Comment by braewoods** [comment]
I don't believe you can do that in a single commit because it requires you to know the hash of the commit you are going to commit and that is impossible to know because it depends on the content of the commit among other things. Any changes to it will necessarily change the resulting commit. The only obvious solution is to commit the update as its own commit so it can know the previous commit's hash.

**Comment by wchen342** [comment]
Ok you are right. Now I recall this is what all the problems around #34 was for. You also helped me realize a bug in my Github Actions build tests which the PKGBUILD there is not pulling the newest commit.

**Pull request merged**
