### PR TITLE
Update to Chromium 80.0.3987.87

### PR DESCRIPTION
**Pull request by tangalbert919**
Issue #33 should probably be closed now, given that VA-API support was added a few major versions ago. If there's still issues, I'll take a look into it.

### CODE REVIEW

**Comment by braewoods** [comment]
@Eloston, I manually reran the validate_with_source test locally and it does pass here so it seems the failure was due to a transient error.

**Comment by wchen342** [comment]
Just FYI, debug build failed with the following error:

```
FAILED: obj/third_party/pdfium/testing/fuzzers/pdf_nametree_fuzzer_impl/pdf_nametree_fuzzer.o 
clang++ -MMD -MF obj/third_party/pdfium/testing/fuzzers/pdf_nametree_fuzzer_impl/pdf_nametree_fuzzer.o.d -DLLVMFuzzerTestOneInput=__attribute__\(\(visibility\(\"default\"\)\)\)\ pdf_nametree_fuzzer -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"n332890-c2443155-1\" -DCOMPONENT_BUILD -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DPNG_PREFIX -DPNG_USE_READ_MACROS -D_FX_CPU_=_FX_X64_ -DPNG_PREFIX -DPNG_USE_READ_MACROS -DPDF_ENABLE_V8 -DPDFIUM_PRINT_TEXT_WITH_GDI -DPDF_ENABLE_V8 -DPDFIUM_PRINT_TEXT_WITH_GDI -DFPDF_IMPLEMENTATION -I../../../ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/src/chromium-80.0.3987.87 -Igen -I../../../ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/src/chromium-80.0.3987.87/third_party/pdfium -I../../../ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/src/chromium-80.0.3987.87/third_party/pdfium -Igen/shim_headers/icuuc_shim -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../../ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/src/chromium-80.0.3987.87/tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O0 -fno-omit-frame-pointer -g1 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-bitwise-conditional-parentheses -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -fPIC -Wshadow -Wno-shorten-64-to-32 -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -D_FORTIFY_SOURCE=2 -D__DATE__=  -D__TIME__=  -D__TIMESTAMP__= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wno-builtin-macro-redefined -Wno-unknown-warning-option -c ../../../ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/src/chromium-80.0.3987.87/third_party/pdfium/testing/fuzzers/pdf_nametree_fuzzer.cc -o obj/third_party/pdfium/testing/fuzzers/pdf_nametree_fuzzer_impl/pdf_nametree_fuzzer.o
../../../ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux/src/chromium-80.0.3987.87/third_party/pdfium/testing/fuzzers/pdf_nametree_fuzzer.cc:5:10: fatal error: 'fuzzer/FuzzedDataProvider.h' file not found
#include <fuzzer/FuzzedDataProvider.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by wchen342** [comment]
Debug build still fails, same error.

**Comment by braewoods** [comment]
I have figured out why this is failing. The missing header is only available in the latest LLVM 10 which isn't even available for download yet it appears. The missing header isn't available in LLVM/Clang 9 which is what most distributions including ARCH currently ships as the latest. So this is not an issue that can be easily resolved for now if we are to continue using the official distribution packaging. I think it would be best to just ignore the failing debug builds or disable the part that needs this header until LLVM has been upgraded as this will also fail over in Debian and Ubuntu builds.

**Comment by wchen342** [comment]
@braewoods I think in that case it's better to make a patch in the main repo that excludes those parts that require LLVM 10, since I don't think LLVM 10 will land on main stream distributions very soon, especially Debian based ones. It is not a good idea to leave a non-functional debug build because we need it to diagnose if anything went wrong.

**Comment by braewoods** [comment]
@wchen342 Is that even feasible? I thought LLVM 10 was a requirement due to the changes in the upstream source.

**Comment by wchen342** [comment]
@braewoods There are other possible solutions like using the header from [llvm master](https://github.com/llvm/llvm-project/blob/master/compiler-rt/include/fuzzer/FuzzedDataProvider.h). It doesn't hurt to try. Also I realized `fuzzer` is not only part of the debug build but also essential for unit testing so this needs to be solved somehow without removing it.

Maybe we can leave it for now and open a separate issue tracking this? @Eloston

**Comment by sxiii** [comment]
So guys do we have something that blocks us from getting 80 to build now? It seems like ungoogled-chromium-ozone (version for wayland) is published & working already. Maybe kinda "backport" their PKGBUILD?

**Comment by braewoods** [comment]
@sxiii Just someone wanting to delay because the debug build is currently broken due to upstream switching to LLVM 10 and by proxy Clang 10. These packages are still unreleased by LLVM upstream so it is something that won't be fixable anytime soon that I can tell. ungoogled-chromium-ozone won't help us because they would have the same problem if they were doing debug builds. Other than that we're just waiting for @Eloston to approve the pull request.

**Comment by jstkdng** [comment]
To add to what @braewoods said, ungoogled-chromium-ozone also has a problem with linking at the last step of build.
```
[ 9752s] [37148/37148] LINK ./chrome
[ 9752s] FAILED: chrome 
[ 9752s] clang++ -Wl,--version-script=../../build/linux/chrome.map -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=8 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=10g:cache_size_files=100000 -Wl,--lto-O0 -fwhole-program-vtables -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -fsanitize=cfi-vcall -fsanitize=cfi-icall -pie -Wl,--disable-new-dtags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o "./chrome" -Wl,--start-group @"./chrome.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lX11 -lX11-xcb -lxcb -lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lXtst -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0 -licui18n -licuuc -licudata -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lcups -lfontconfig -ldbus-1 -lresolv -lgio-2.0 -lz -lwebpdemux -lwebpmux -lwebp -lfreetype -ljpeg -lexpat -lharfbuzz-subset -lharfbuzz -ldrm -lm -lopus -lavcodec -lavformat -lavutil -lvpx -lXrandr -lre2 -lpci -lXss -lasound -lpulse -lsnappy -latk-1.0 -latk-bridge-2.0 -lva -lpangocairo-1.0 -lpango-1.0 -lcairo -lxml2 -latspi -lFLAC -lminizip -lgtk-3 -lgdk-3 -lcairo-gobject -lgdk_pixbuf-2.0 -lxslt -llzma -llcms2 -lopenjp2
[ 9752s] ld.lld: error: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../lib64/libopenjp2.so: undefined reference to __exp_finite
[ 9752s] ld.lld: error: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../lib64/libopenjp2.so: undefined reference to __exp2_finite
[ 9752s] clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
[ 9752s] ninja: build stopped: subcommand failed.
[ 9752s] ==> ERROR: A failure occurred in build().
[ 9752s]     Aborting...
```
It seems system openjpeg2 is broken, dunno if you are having this problem as it seems the debug builds aren't reaching the final linking process, or am I the only one with this problem?
Some additional changes might be needed, maybe. I'm still testing some fixes.

**Comment by sxiii** [comment]
> @sxiii Just someone wanting to delay because the debug build is currently broken due to upstream switching to LLVM 10 and by proxy Clang 10. These packages are still unreleased by LLVM upstream so it is something that won't be fixable anytime soon that I can tell. ungoogled-chromium-ozone won't help us because they would have the same problem if they were doing debug builds. Other than that we're just waiting for @Eloston to approve the pull request.

Thanks for your answer. Can I meanwhile do a release build? How can I do that?

**Comment by braewoods** [comment]
@sxiii I would assume you could do so by following the build instructions included in the remote branch of this pull request. All reports indicate that a regular build should succeed.

**Comment by wchen342** [comment]
@jstkdng My test run of release build didn't reach the end too because of the jumbo problem, so I didn't know whether this version will build successfully. I came across some posts though saying it could probably be solved by adding `-lm` or `-fno-builtin`.

**Comment by tangalbert919** [comment]
When it comes to the debug build, I should point out that the header `FuzzedDataProvider.h` does exist in LLVM 9, but in a slightly different [place](https://github.com/llvm/llvm-project/blob/release/9.x/compiler-rt/lib/fuzzer/utils/FuzzedDataProvider.h).

I can make a patch for this, although that patch will only last until LLVM 10 officially comes out (which is sometime at the end of this month).

**Comment by braewoods** [comment]
@tangalbert919 How would that help? AFAIK, no LLVM 9 distribution packages include that header at all. I have searched them already and I cannot find any header named `FuzzedDataProvider.h`. That is why I assumed it was LLVM 10 only.

**Comment by wchen342** [comment]
@braewoods 

libFuzzer existed [since LLVM 5.0.0](https://releases.llvm.org/5.0.0/docs/LibFuzzer.html). THe header file just [doesn't get included in the Arch `compiler-rt` ](https://bugs.archlinux.org/task/47389). Debian for example has a [`libfuzzer-9-dev` package](https://packages.debian.org/sid/libfuzzer-9-dev) which comtains the static lib file, but not the header. The header file [can be used standalone per original repo](https://github.com/google/fuzzing/blob/master/docs/split-inputs.md#fuzzed-data-provider).

**Comment by tangalbert919** [comment]
So if we want to fix that error that is interfering with debug builds, we need to add that header manually. We can do that through a patch, along with editing the files that require that specific header.

**Comment by Eloston** [comment]
Created #58 to address failing debug builds.

**Pull request merged**
