### PR TITLE
PKGBUILD: Upgrade to 90.0.4430.212

### LINKED ISSUE #126: Update to Chromium 90.0.4430.212
Could we update to 90.0.4430.212? 

Based on https://omahaproxy.appspot.com/ updates >)

### PR DESCRIPTION
**Pull request by networkException**
Resolves #126

### CODE REVIEW

**Comment by networkException** [comment]
I never thought about this, the pull request token understandably has no access to the container registry. I will wait for https://github.com/networkException/ungoogled-chromium-archlinux/runs/2583439502 to finish, which is based on effectively the same changes as this and merge then.

**Comment by braewoods** [comment]
You can push these changes directly to the repository and then do a manual push.

**Comment by braewoods** [comment]
Otherwise you can do it from your fork with your own OBS project and credentials.

**Comment by networkException** [comment]
I know, I just wanted to have a full build and confirmed that it also works on runtime. I might look into OBS in the future but for now Actions is my main tool for that.

In the future, the workflow will use an artifact to transfer the docker image from job to job

**Pull request merged**
