### PR TITLE
Adding cachy-repo for prebuilt ungoogled-chromium

### PR DESCRIPTION
**Pull request by ptr1337**
providing ungoogled chromium compiled with -march=x86-64 and -march=x86-64-v3

### CODE REVIEW

**Comment by ptr1337** [comment]
> > No problem, i just use a private github repo for the GH actions, since they run on my server with a 5900x.
> > At Librewolf/Firefox/Cachy-Browser you can see the compile flags which are used to compile it. I dont know if this also works at ungoogled-chromium.
> 
> Firefox uses a completely different build system. My requirement is that the PKGBUILD file that is used to build the ungoogled-chromium package is public, if that is in a git repository or in the final package itself that doesn't matter.
> 
> If you look at the content of the currently only ungoogled-chromium package that is downloadable on your file server it contains the checksum of a PKGBUILD file, _that_ extact file needs to be public
> 
> image

So, then i gonna setup a PKGBUILD repo with external packages an their .SRCINFO and compile it via github action. 

Is it okay for you if i provide only one directory and .SRCINFO for both -march? or you could change also the PKGBUILD and add x86_64_v3, then there will be this no problem.

**Comment by networkException** [comment]
Its fine as long as its possible to obtain the original PKGBUILD file (matching checksums), if the -march needs to be changed manually thats ok as well but should probably be documented

**Comment by ptr1337** [comment]
> Its fine as long as its possible to obtain the original PKGBUILD file (matching checksums), if the -march needs to be changed manually thats ok as well but should probably be documented

At the moment i clone your repo and change the march, should i use the AUR PKGBUILD or this repo ? 
Since most time this one is faster updated.

https://github.com/CachyOS/PKGBUILDs

Will be in this repo added.

**Comment by networkException** [comment]
It doesn't matter too much if you use the PKGBUILD file from this repo or the one from the AUR, I'd say that this one *usually* is a bit faster tho because sometimes I push the update tag to Eloston/ungoogled-chromium myself and alongside that here as well.

**Comment by ptr1337** [comment]
@networkException 

Fixed with that repo and action: 

https://github.com/CachyOS/PKGBUILDs

**Pull request merged**
