### PR TITLE
Upgrade to 89.0.4389.90

### PR DESCRIPTION
**Pull request by networkException**
This first badge of changes do not pass the build, however make it quite far.

The CI pipeline got adjusted to allow for a longer build, the time needed for the previous
steps strongly suggests the need of this change. If it was really needed can only
be checked by a passing build however

The package build definitions have also been updated, setting the new chromium
and ungoogled-chromium version as well as applying different patches for libstdc++
build support

The subpixel-anti-aliasing-in-FreeType-2.8.1 patch has been removed as it now matches upstream source
files

---

The build fails at `out/Release/gen/shim_headers/opus_shim/third_party/opus/src/include/opus.h` as the include in line 5 can not be resolved. I was able to get it to build fully on my host machine
by manually adding the header files from chromium upstream and resuimg the build.

I am not very knowledable in the topic and happy to have been able to build the version at all. I'm pretty
sure that the way I was able to compile isn't intended however, thats why this is still a draft for now.

I would appreciate any help towards getting the CI to pass.

### CODE REVIEW

**Comment by networkException** [comment]
Ok, thanks to some searching around I found the patches for the arch linux chromium package (that the package files of this project are based on as I'm guessing). I will quickly do some tests locally and then add the updated patches from there to this pull request as well.

**Comment by networkException** [comment]
I'm confused, what is the actual purpose of this repostitory? Sure, it contains the needed CI configuration to build on github and its also the place people would probably first look for a download. Still the aur configuration is located in a different repository, even though the changes should in theory apply to both always.

**Comment by networkException** [comment]
Because now by the looks of it an update to this repo could basically be made by pulling the aur changes,

**Comment by jstkdng** [comment]
Yeah, I tend to first update the aur then update this repo. They are on different repos because I'm using aurpublish on it and it needs a different folder structure. https://github.com/jstkdng/aur
Still, help is appreciated even if it is just pulling the changes from the aur. Also didn't know another CI step was required.

**Comment by networkException** [comment]
Alright that makes sense, I think I will look into future version updates for this repo then and just collect the required patches from the arch chromium package and your ungoogled-chromium aur package.

**Comment by nikolowry** [comment]
For my local checkout, I added the AUR repo as a @remote named `aur` and pull in the changes by running `git pull aur master --allow-unrelated-histories`.

**Comment by networkException** [comment]
I was thinking about bridging the repos as well however I'm not sure what do to. Should this repo be the source? Should submodules be used or should the CI pull files from the aur? 

In a perfect world I'd imagine a central place for all the patches required, with an aur package for building from source and one -bin, as well as a github release, generated by the CI

**Comment by jstkdng** [comment]
Previously, the AUR would pull the changes from here once it was updated, then I joined as a member here and also became a co-maintainer on the AUR, so pretty much I took over both sides. Most arch users will download from the AUR than from here so I gave the AUR more priority. Not sure how to link both repos though.

**Comment by networkException** [comment]
If you are willing to look into such changes I would suggest opening a new issue for discussion and thoughts on how to make updates more uniform and efficient. I see that arch users probably look primarily in the aur, however at least for me it is quite the hassle to compile chromium from source as I just have a laptop. Thats why I would pledge for an ungoogled-chromium-bin package additionally to a github release.

**Comment by jstkdng** [comment]
I actually also maintained a -bin package but it was taken down. Best option is to use any of the binary repositories listed on the README. Even I have a repo that has uc binaries.
A github action could be used to pull changes from the aur from time to time.

**Comment by networkException** [comment]
Oh ok, unfortionate that it got taken down. I guess just hard coding some commit hash and updating it here to trigger a new actions build would be the easiest way to have a unified repository then.

I think I will look into implementing that in the next few days. Until then, chromium 89.0.4389.90 will probably be published (some security fixes). Depending on when https://github.com/Eloston/ungoogled-chromium/pull/1433 gets merged I might just use this pr and update the files

**Comment by nikolowry** [comment]
I don't think it matters too much which repo is the "source of truth", but the `PKGBUILD` should always be identical between the two.

The reason I do local builds via `makepkg`  is so I can apply some opinionated UI patches, and it's been pretty confusing tracking down the "right" changes the past couple releases. Regardless, great job everyone for keeping everything up-to-date and maintained!

**Comment by jstkdng** [comment]
The PKGBUILD is identical, just the comments on the top are different. On the AUR I have the current maintainer's name there for credit whilst here I only have Ungoogled Software Contributors

**Comment by networkException** [comment]
Would that be a legal problem if this repo would just build the aur package in CI?

**Comment by jstkdng** [comment]
You mean this repo only having files for github actions?

**Comment by networkException** [comment]
yes

**Comment by jstkdng** [comment]
I'll accept this pr but open an issue for further discussion on the topic.

**Pull request merged**
