### PR TITLE
Added new github workflow

### PR DESCRIPTION
**Pull request by jstkdng**
This should solve #34

### CODE REVIEW

**Comment by jstkdng** [comment]
Another workflow could be created to build ungoogled chromium but that would take quite a while, we should use the OBS for building as we get more compute power there.
Finally, the process could take less if it is only installed the make depends, but that update goes to the action reporitory, not here.

**Comment by jstkdng** [comment]
Finally, I think the validate_* actions should be deleted in favor of this one as this action checks both the makepkg and source and takes less time. 5 min vs 14 min in total.

**Comment by wchen342** [comment]
Isn't it that the version of `PKGBUILD` used in Actions will still be the verions in `master` (because of the source array)?

**Comment by jstkdng** [comment]
The actions/checkout step will get the latest ref in the pr.

**Comment by wchen342** [comment]
But `makepkg` will download another copy under `src` according to [https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/PKGBUILD#L39](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/PKGBUILD#L39) and use that to build, no?

**Comment by jstkdng** [comment]
yes, that would be correct. Only way to fix that would be to not download the repository again and just add the patches in the source array.

**Comment by jstkdng** [comment]
out of all the patches only a few are required for arch. Could make another PR to move all the patches into the array.

**Comment by wchen342** [comment]
Are you talking about the patches under `patches/archlinux`? What about the other patches in `debian_buster` and `inox-patchset`?

**Comment by jstkdng** [comment]
the ones in debian buster arent required and I think only 1 from inox is required I think.

**Comment by wchen342** [comment]
Had a quick look, I think you are right. Feel free to make the PR and update this one.

**Comment by jstkdng** [comment]
is it ok to remove the other validate_* actions?

**Comment by wchen342** [comment]
Yes, but there is another problem. I think it will probably be better if we create a repository under `ungoogled-software` which holds your custom actions, decreasing external dependencies. I cannot do that though so I need @Eloston's approve on this.

**Comment by Eloston** [comment]
I'd prefer the actions to be in the same repo if possible (easier to maintain and manage). Otherwise I agree with @wchen342 that we should keep all our code under the ungoogled-software organization.

If it can't be done by merging CI config files (or it's not as clean), you could also consider creating an orphaned branch with the config you need via `git switch --orphan BRANCH_NAME` (in older git, use checkout)

**Comment by jstkdng** [comment]
Well, the action is just another repository, you could fork the action into the organization to have some more control, I dont mind editing the workflow to point to it.

**Comment by jstkdng** [comment]
ok, had to update the action as it was failing due to arch updates. I'm also not sure how to remove the cirrus tasks. Do I just remove the .cirrus files on the root? Or does @Eloston have to do anything else behind the curtains? Final thought for now, I think the obs action should be run on a tag creation to avoid constantly building.

**Comment by wchen342** [comment]
> Do I just remove the .cirrus files on the root?

Yeah you just need to remove the cirrus files.

> the build actions should be run on a tag creation to avoid constantly building.

Probably, but we don't have tags here in the Arch repo. Probably we should do that starting from next version?

**Comment by jstkdng** [comment]
> Yeah you just need to remove the cirrus files.

fair enough, will do 

> Probably we should do that starting from next version?

I think we should, or at least not yet, Maybe until I figure how to automate updating github, the aur and obs.

**Comment by wchen342** [comment]
Ok just need to wait @Eloston to fork the Actions repo and this is good.

**Comment by selurvedu** [comment]
@wchen btw, the repo can be transferred from a user to an org, and then forked from an org to user account. If the fork is going to become the upstream, I find this way better than simply forking into an org, because the "Forked from" reference will stay in the new-upstream repo forever, unless one of the following actions is taken:
1. The owner of the parent repo contacts the github support and asks to change the parent repo.
2. The parent repo is deleted, and the oldest fork becomes the new parent.

**Comment by jstkdng** [comment]
@selurvedu in the first place the action has nothing to do with UC, so there is no inherent need to fork it in the first, other than for more control over the code or stability.
But hey, its up to them why they fork it.

**Comment by Eloston** [comment]
Forked as https://github.com/ungoogled-software/archlinux-check-pkgbuild

**Pull request merged**
