### PR TITLE
Update chromium to 83.0.4103.116

### PR DESCRIPTION
**Pull request by jstkdng**
Also cleaned up the workflow

### CODE REVIEW

**Comment by jstkdng** [comment]
Welp, uploading artifacts is still broken. At least the obs build was succesful. https://build.opensuse.org/package/live_build_log/home:justkidding:arch/ungoogled-chromium/standard/x86_64
Guess this can be merged. @wchen342 @braewoods

**Comment by wchen342** [comment]
@jstkdng The OBS one is manually run by you, not sent by workflow right? I think @braewoods is working on a repo to keep the secrets of OBS but that shouldn't have been finished yet.
There are all kinds of unexpected failures in Actions, that is why I wrapped key parts in my old workflow files in for loops for retries. It was kind of ugly though.

**Comment by wchen342** [comment]
BTW was the OBS build using the latest version of llvm/clang on Arch? I am asking because I hit a strange link-time issue related to standard libraries when cross-compiling on Arch this week and I have to switch to `llvm-git` (which is llvm 11.0.0) to solve it. It will probably not occur on Linux version though since it's the same architecture.

**Comment by jstkdng** [comment]
I have a workflow that triggers an obs build on my own repo. https://github.com/jstkdng/ungoogled-chromium-archlinux/blob/master/.github/workflows/build.yml#L23

Regarding the llvm version, the OBS build is using clang 10.0.0-3 and llvm 10.0.0-2 according to the logs. 
image
image

**Comment by jstkdng** [comment]
If you need llvm-git just build it on the obs and reference your own home project in the repositories for your home project.
image

**Comment by wchen342** [comment]
I found my problem is actually caused by `lld`, downgraded it to `10.0.0-2` solved the problem. No idea why though.
I will merge this once the workflow finishes.

**Comment by jstkdng** [comment]
Alright then.
Surprisingly, this workflow might actually finish, will you create a release with the resulting binaries?

**Comment by wchen342** [comment]
You mean for this specific version? But if we do this once then we should do it every time. I think it's better wait until either Actions are more stable or the OBS workflow is online.
Creating release can actually be done within workflow btw.

**Comment by jstkdng** [comment]
That would create a release on my fork. But, oh well, I'll try to add another job to actually create a release. Probably for next update as 83.0.4103.116-2 came out today.

**Comment by jstkdng** [comment]
finally, a sucesfull buils. Will test it asap

**Comment by jstkdng** [comment]
Alright, that should do it. OBS build succeded, github one will take a while.

**Comment by wchen342** [comment]
Well the Actions failed again. But since OBS is good I am merging this.

**Comment by jstkdng** [comment]
People on the AUR seem to be having the same issue as you @wchen342 . Kinda weird, did you manage to figure out the problem?

**Comment by wchen342** [comment]
That guy's problem is different than mine. My error is related to `-wrap` so I'm pretty sure it's the linker.
Ok so I saw an update on the problem, it seems it's the LTO.

**Pull request merged**
