### PR TITLE
Update to Chromium 90

### PR DESCRIPTION
**Pull request by braewoods**

### CODE REVIEW

**Comment by braewoods** [comment]
This is the current progress on Chromium 90. Unfortunately I ran into an issue during the build I have no idea how to resolve. There's no meaningful data in the output and I don't know chromium well enough to debug it for the moment.

**Comment by networkException** [comment]
I think I fixed the CI failure in this commit on my pr branch https://github.com/networkException/ungoogled-chromium-archlinux/commit/f97ffc14b15786293290eac8f442b618ba67eced

**Comment by braewoods** [comment]
That's not the same error I ran into but it's still something that needs to be fixed elsewhere.

**Comment by braewoods** [comment]
The error is in the OBS log here:
https://build.opensuse.org/build/home:ungoogled_chromium:testing/Arch/x86_64/ungoogled-chromium-arch/_log

**Comment by networkException** [comment]
Ah I didn't think about OBS.

**Comment by braewoods** [comment]
I presume we'll run into it everywhere since it also showed up in my container builds.

**Comment by networkException** [comment]
Interesting, github ran further. I'm guessing https://github.com/archlinux/svntogit-packages/blob/packages/chromium/repos/extra-x86_64/add-clang-nomerge-attribute-to-CheckError.patch is needed to build futher

**Comment by braewoods** [comment]
I added some patches Arch was using and we were not. Though I'm not sure what difference it makes right now.

**Comment by braewoods** [comment]
Weird. Ok, so the flatc utility is apparently receiving or raising SIGTRAP when run during the build process. I have no idea why except maybe the codegen is weird.

**Comment by braewoods** [comment]
I think I've found something but still need to see if it builds. The way we handle python2 appears to make a difference in the build progression.

**Comment by braewoods** [comment]
Nope, still nothing. Ok. Time to see if justkdng's effort is any better.

**Comment by braewoods** [comment]
@jstkdng Were you able to build chromium 90 on Arch? I keep getting errors about flatc which is killed by SIGTRAP. It happens in my LXD container and also on OBS. I'm at a loss for why it is happening.

**Comment by jstkdng** [comment]
yeah, I'm also getting that build issue, now I wonder how the arch dev's were able to build chromium. Maybe a recent python upgrade causing this?

**Comment by braewoods** [comment]
No idea but we need to resolve this somehow. Can you build the Arch chromium as is?

**Comment by braewoods** [comment]
I am testing the build again today with the system updates that were available.

**Comment by braewoods** [comment]
Still fails. I'll merge this for now. It should build once the upstream issue is fixed.

**Pull request merged**
