### PR TITLE
Fix patches for 81.0.4044.113-1

### PR DESCRIPTION
**Pull request by Stephen-Seo**
Note the issue with the final linking step is not fixed in this PR (use_system_libopenjpeg2) #57 .

A few patches were added to fix compiler errors.

Several patches were removed since they were already applied upstream.

### CODE REVIEW

**Comment by wchen342** [comment]
Can you also add `libffi` to dependencies? I was checking way Actions failed and found the library is missing:
```
make: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
```

**Comment by Stephen-Seo** [comment]
> Can you also add `libffi` to dependencies? I was checking why Actions failed and found the library is missing:
> 
> ```
> make: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
> ```

I think libffi is a direct dependency of python and an indirect dependency of make, both of which should cause the build to install it before building, but I'll add it to the dependency list anyways.

**Comment by wchen342** [comment]
@Stephen-Seo The command I used to test building is `makepkg -s`, which supposedly should install all dependencies so I'm not sure why `libffi` was not there. I will try to test a little more in my fork.

**Comment by Stephen-Seo** [comment]
> @Stephen-Seo Sorry my fault. I forgot I haven't pushed the fix for unability of running on pull request in Actions yet. I think this is good to go.

In that case, should I revert my commit adding libffi as a dependency?

**Comment by wchen342** [comment]
@Stephen-Seo Yeah the extra dependency is not necessary.

**Comment by Eloston** [comment]
@wchen342 The changes in this PR looks pretty straight-forward to me. In the future, feel free to merge them :+1:

**Pull request merged**
