### PR TITLE
patches: Update for 76.0.3809.87

### PR DESCRIPTION
**Pull request by xsmile**
@Eloston I removed most of the Debian patches this time, as you suggested a while back.

### CODE REVIEW

**Comment by jstkdng** [comment]
is the gcc-9 patch really no longer needed?

**Comment by xsmile** [comment]
@jstkdng It is not, see the patches included in the original chromium package for Arch Linux.

**Comment by jstkdng** [comment]
@xsmile yeah, just checked. I'll add the changes to my repo.

**Comment by jstkdng** [comment]
It seems Eloston hasn't updated the tags in his repo, so right now this PKGBUILD won't compile.

**Comment by Eloston** [comment]
@jstkdng Just added a tag.

**Pull request merged**
