### PR TITLE
Move patch files to root dir

### PR DESCRIPTION
**Pull request by jstkdng**
Also renamed some patches to the same name from arch.

### CODE REVIEW

**Comment by jstkdng** [comment]
Some checks might fail though.

**Comment by Eloston** [comment]
Tangential curiosity: How does Arch manage a series of patches? Do they have something like `quilt`, or does everyone just manually apply/revert patches?

**Comment by jstkdng** [comment]
They apply patches manually. Even if there are a lot of them.

**Comment by wchen342** [comment]
@jstkdng It seems a GPU fix is missing? The build failed with error in `media/gpu/vaapi/vaapi_picture_tfp.cc`.

@Eloston Technically it is still possible to use `quilt`. You just need to copy `series` into the source array manually.

**Comment by jstkdng** [comment]
didn't notice you enabled vaapi on the flags
just added the compile fix and some additional patches I use. It should build now

**Comment by wchen342** [comment]
Ok, the file `chromium-drirc-disable-10bpc-color-configs.conf` is in the sources but the actual file is missing.

**Comment by jstkdng** [comment]
Oops, forgot that file. Added the install command in the package function

**Comment by wchen342** [comment]
Also why removing the `provides` and `conflicts` sections? Won't UC overwrite the `chromium` executable in `/usr/bin`?

**Comment by jstkdng** [comment]
It is still on the pkgbuild, just moved it after the sums array

**Comment by wchen342** [comment]
Looks good now.

**Pull request merged**
