### PR TITLE
Update to 81.0.4044.129-1

### PR DESCRIPTION
**Pull request by braewoods**

### CODE REVIEW

**Comment by wchen342** [comment]
@Eloston I wonder whether these lines regarding versions are written in the way the are for a reason, or they are just legacy codes left over when the repositories splitted?

**Comment by braewoods** [comment]
No idea. I thought it was a minor improvement I could make without changing any important behavior. I was wanting to make it possible to use the PKGBUILD without network access as my first step towards OBS support as build environments don't always have network access.

**Comment by wchen342** [comment]
I think the Arch update today caused a new error while building, I saw it both on AUR and my Actions:

```
../../v8/src/objects/js-number-format.cc:1227:15: error: no member named 'getAllFieldPositions' in 'icu_67::number::FormattedNumber'
    formatted.getAllFieldPositions(*fp_iter, status);
    ~~~~~~~~~ ^
1 error generated.
```

**Comment by braewoods** [comment]
No I haven't. I assumed it was probably due to something Arch does with their libraries as that error doesn't occur with the Debian builds at all.

**Comment by jstkdng** [comment]
A new patch is required as icu67 arrived in the stable repositories: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=d707309c705afb838241770e2358cb43e65680aa

**Comment by braewoods** [comment]
Ok. I'll add the patch to my PR.

**Comment by Rowisi** [comment]
Now I have to recompile it :man_facepalming:

**Comment by Eloston** [comment]
@wchen342 

> I wonder whether these lines regarding versions are written in the way the are for a reason, or they are just legacy codes left over when the repositories splitted?

I'm not sure what you're referring to specifically, but I think the use of curl was always unnecessary. These changes are great.

The adding of the ungoogled-chromium and Arch Linux revision numbers is a hacky design decision because Arch doesn't seem to like non-integer revision numbers like `1.1` in all other platforms. Feel free to improve this as you see fit.

**Pull request merged**
