### PR TITLE
85.0.4183.121 upgrade

### PR DESCRIPTION
**Pull request by jstkdng**
New gn is needed until we reach chromium 86.

### CODE REVIEW

**Comment by wchen342** [comment]
You mean **old** gn?

Also @Eloston I will probably move to another distro soon so probably you should just make @jstkdng the admin of this repo.

**Comment by jstkdng** [comment]
well, its a new package but an old version, in a sense is both new and old.

**Comment by Eloston** [comment]
> Also @Eloston I will probably move to another distro soon so maybe you should just make @jstkdng the admin of this repo.

Done.

**Comment by wchen342** [comment]
> well, its a new package but an old version, in a sense is both new and old.
> Edit: actions are failing due to the old-new gn, will have to update it.

That's confusing. The Actions file need to be improved so that errors are shown as errors on the webpage I guess?

**Comment by jstkdng** [comment]
Upstream arch upgraded to 85.0.4183.121 before they updated gn, so they didn't face this [issue](https://i.imgur.com/33UjwWH.png). After chromium-vaapi users were affected, a TU created the package gn-m85 as a fix until chromium reaches v86.
> The Actions file need to be improved so that errors are shown as errors on the webpage I guess?

Yeah, I'll update it on another PR.

**Comment by jstkdng** [comment]
OBS build was succesful https://build.opensuse.org/package/live_build_log/home:justkidding:arch/ungoogled-chromium/standard/x86_64

Will merge now.

**Pull request merged**
