### PR TITLE
chromium upgrade to 83.0.4103.97

### PR DESCRIPTION
**Pull request by jstkdng**

### CODE REVIEW

**Comment by wchen342** [comment]
LGTM.

**Comment by Rowisi** [comment]
Its missing a fix from the [chromium 83.0.4103.97-2](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=41b7e682bd3a4445ccc97ede268834a4255f3c3f) update

**Comment by wchen342** [comment]
Does that have effect on actually program?

**Comment by Rowisi** [comment]
@wchen342 no, but from [FS#66890](https://bugs.archlinux.org/task/66890) it seems it has something to do with metadata.

**Comment by wchen342** [comment]
I see. There is no harm to include it though, so wait for @jstkdng to update it.

**Comment by jstkdng** [comment]
That should do it

**Comment by wchen342** [comment]
Ok I'm merging it.

**Pull request merged**
