### PR TITLE
Discussion: Unify package build files

### PR DESCRIPTION
**Pull request by networkException**
At the current state, this pull request removes all package build files from this repository.
Instead, the aur package will get pulled from aur.archlinux.org and the GitHub Actions workflow
then builds a production binary.

Note that while this is the current state of the pull request, it is mainly meant for discussing how
the build files can be unified in a good way.

### CODE REVIEW

**Comment by networkException** [comment]
Sadly this seems to run into storage limitations of a github runner

**Comment by jstkdng** [comment]
A better option to clone is to modify the action yml file. Modifying the actions/checkout step on all jobs would be a better solution in my opinion.

**Comment by networkException** [comment]
Wouldn't the runner then miss access to the shell scripts in .github? From my understanding either one of the repos has to be cloned anyways.

Also any clue about the build failure in my latest commits?

**Comment by jstkdng** [comment]
>Wouldn't the runner then miss access to the shell scripts in .github

Hmmmm, yeah you're right, we'd lose access to the scripts.

> Also any clue about the build failure in my latest commits?

I also have those issues on my obs build logs, probably the latest upgrade of libva broke the build.

**Comment by braewoods** [comment]
It's now building again. So what else is stopping this?

**Comment by networkException** [comment]
Last time github also had problems with extracting some archive, it overflowed the runners disk size. I will update the commit hash and see if it runs to completion this time

**Comment by networkException** [comment]
Ok that built, even though github doesn't seem to show the status badge here's the log https://github.com/networkException/ungoogled-chromium-archlinux/actions/runs/729735115

**Comment by jstkdng** [comment]
Since @braewoods seems ok with this then I'll accept this pr. Before that please fix the latest conflict.

**Comment by networkException** [comment]
The conflict is a result of `PKGBUILD` being removed on this branch while the file on master got an update 3 days ago.

Should I just import the updated file and make sure that existing files would override those coming from the aur?

**Comment by networkException** [comment]
I thought about what this pull request is doing a bit and I came to the conclusion that it's not an ideal solution and should maybe not be merged.

Essentially it would just move the "source of truth" from this repo to the aur repo. 
Now at first glance that sounds good, it removes duplication of building logic and patches and puts everything in a central spot.
But actually by doing that it's creating new problems, making the code less accessible due to it being "hidden away" by git clones in the github workflow somewhere. This of course could be communicated through the readme but still the sort of "open" community aspect of the ungoogled-software organization as a central point for build logic targeting different distributions would go away to a significant extent.

Instead of using existing build files from the aur repo to build a release here using github actions, why not use this repo as a source of truth for aur build files, obs build, github release build and maybe also aur bin files (I'm sure the issue of the previous package being taken down can be resolved in case it would somehow affect a republish). I quite like the way a new chromium release gets a new issue in the ungoogled-chromium repository, maybe something similar could create a new issue or even branch for work on a new version of ungoogled-chromium here. A description would point towards the arch linux chromium package files as well as the chromium patchset for gcc building, giving also less experienced developers the ability to start work on a new release.

Again, those are my thoughts on the p
topic. It's really the proposal for a more long term goal however, so if for now merging this pull request is fine then I don't mind as well. I would certainly help to get this repository to a point matching the ideas described above as best as I can, but there are many things that need to be configured that are outside the scope of the source as well.

**Comment by networkException** [comment]
Closing this because I have changed my mind about where build files for the project should be stored, further explained in the comment above

**Pull request closed without merging**
